added git and youtube icons @social links
ritinlug/ritinlug.org pull request #10
Opened 2017-09-16 18:08 UTC by saurabhlondhe

2017-09-16 18:19 UTC, bhavin192 requested changes
Make it inline with other two logos, you can see the deployed preview here 
https://deploy-preview-10--ritinlug.netlify.com

2017-09-16 18:19 UTC, bhavin192 commented on index.html
> +                 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-left">
We don't have YouTube channel, please remove it at least for now

2017-09-16 18:19 UTC, bhavin192 commented on index.html
> +                 <div class="col-lg-4 col-lg-offset-2 col-md-4 col-md-offset-2 col-sm-4 col-sm-offset-2 col-xs-4 col-xs-offset-2 text-right">
The color of the logo should match with other logo colors

2017-09-16 19:12 UTC, bhavin192 approved these changes

2017-09-16 19:38 UTC, shaharao commented
LGTM

2017-09-16 19:44 UTC, akshaygin reviewed
- Make it inline with other logos
- github logo should square in shape, similar to other
- Make github logo responsive(It should have properly placed for different devices)

2017-09-18 18:24 UTC, bhavin192 requested changes
Please submit only one change per PR
Revert these changes of the README.md

2017-09-18 18:38 UTC, bhavin192 approved these changes

2017-11-14 18:14 UTC, merged